export const strings: Record<string, any> = {
  appName: "Sakthi",
  apiKeyLabel: "Gemini API Key",
  tagline: "Nurturing you, gently.",
  howAreYou: "How are you, mama?",
  logHeart: "Just a tap to log your heart.",
  memoryVault: "Memory Vault",
  vaultDesc: "Store the little things.",
  ashaChat: "Chat with Asha",
  ashaDesc: "Your caring companion.",
  breatheWithAsha: "Breathe with Asha",
  breatheDesc: "A moment for your soul.",
  start: "Start", stop: "Stop", breathe: "Breathe",
  breatheIn: "Breathe In...", hold: "Hold...", breatheOut: "Breathe Out...",
  peace: "Peace",
  reminders: "Gentle Reminders",
  water: "Sip some water", rest: "5 mins of deep rest", tea: "Warm tea for you",
  moodJourney: "Mood Journey",
  noMoods: "No entries yet. Start today.",
  fluctuations: "Mood Fluctuations (Last 7 Logs)",
  searchMemories: "Search your memories...",
  putWhere: "Where did I put the...",
  addMemory: "Add",
  noMemories: "Your cognitive offloader is empty.",
  noMatches: "No matches found.",
  ashaDidi: "Asha", ashaSaheli: "Your companion, always here.",
  ashaGreeting: "Hello, dear. I'm here for you. How are you feeling today?",
  typeHeart: "Type your heart out...",
  home: "Home", mood: "Mood", vault: "Vault", asha: "Asha", help: "Help",
  selfCare: "Self-Care Checklist",
  level5: "Feeling Radiant", level4: "Doing Okay", level3: "Just Being", level2: "A Bit Heavy", level1: "Feeling Low",
  babysLast: "Baby's Last...",
  lastFeed: "Last Feed", lastSleep: "Last Sleep", lastDiaper: "Last Diaper",
  justNow: "Just now", ago: "ago",
  circleOfHope: "Circle of Hope",
  momWin: "Log a 'Mom Win'", winPlaceholder: "What went well today?",
  settings: "Settings",
  apiKeyPlaceholder: "Paste your API key here",
  apiKeyHelp: "Get a free key from Google AI Studio",
  save: "Save", close: "Close",
  chatNeedsKey: "To chat with Asha, please add your free Gemini API key in Settings (tap the gear icon).",
  chatError: "Something went wrong. Please check your API key in Settings and try again.",
  clearChat: "Clear Chat",
  darkMode: "Dark Mode",
  notifications: "Reminders",
  notificationsDesc: "Get gentle reminders for water, rest & vitamins",
  exportData: "Export My Data",
  exportDesc: "Download all your mood and memory data",
  disclaimer: "Important Notice",
  disclaimerText: "Sakthi is a wellness companion, not a medical tool. It does not replace professional medical advice, diagnosis, or treatment. If you are experiencing a medical emergency, please contact your local emergency services immediately.",
  about: "About Sakthi",
  aboutText: "Made with love for every mama. Sakthi means 'power and energy' in Tamil.",
  helplines: "Helplines",
  babyGrowth: "Baby Growth",
  tips: "Tips",
  resources: "Resources",
  emergencyHelp: "Emergency Helplines",
  emergencyDesc: "You are not alone. Help is always available.",
  callNow: "Call",
  textNow: "Text",
  milestones: "Developmental Milestones",
  parentingTips: "Parenting Tips",
  usefulLinks: "Useful Resources",
  addNote: "Add a note...",
  weeklyMoodSummary: "This Week",
  avgMood: "Average Mood",
  totalEntries: "Entries",
  trend: "Trend",
  trendUp: "Improving",
  trendDown: "Needs care",
  trendStable: "Stable",
  welcomeTo: "Welcome to",
  loginDesc: "Your gentle postpartum wellness companion",
  yourName: "Your name",
  babyName: "Baby's name (optional)",
  getStarted: "Get Started",
  continueAsGuest: "Continue without signing in",
  skip: "Skip",
  affirmations: [
    "You are doing a wonderful job, even on the hard days.",
    "Your baby loves you for exactly who you are.",
    "It is okay to ask for help. You don't have to do this alone.",
    "You are recovering, growing, and learning every single day.",
    "Your worth is not measured by your productivity today."
  ],
  circleMessages: [
    "You are not alone. We are all in this together.",
    "It's okay to have a messy house and a happy baby.",
    "Your best is more than enough.",
    "Taking care of yourself is part of taking care of your baby.",
    "This phase is hard, but you are stronger."
  ],
  chatSuggestions: [
    "I'm feeling very overwhelmed today.",
    "I can't remember where I put the baby's medicine.",
    "Tell me something encouraging.",
    "I feel like I'm not doing enough."
  ],
  checklist: [
    { id: '1', text: 'Drank 8oz water' },
    { id: '2', text: 'Took vitamins' },
    { id: '3', text: '5 min sunlight' },
    { id: '4', text: 'Ate a protein snack' },
  ],
  gratitudeTitle: "Today's Gratitude",
  gratitudePlaceholder: "I'm grateful for...",
  saveGratitude: "Save",
  gratitudeSaved: "Saved with love!",
  backupReminder: "Your data lives on this device only. Export to keep it safe.",
  wellnessTip: "Wellness Tip",
  wellnessTips: [
    "Skin-to-skin contact releases oxytocin and helps you both feel calm.",
    "Your body needs 6-8 weeks to begin recovering. Be gentle with yourself.",
    "Texting one friend today can make a real difference in how you feel.",
    "Try the 5-4-3-2-1 technique: 5 things you see, 4 you touch, 3 you hear, 2 you smell, 1 you taste.",
    "Postpartum hair loss is normal and temporary. Your hormones are adjusting.",
    "A 10-minute walk outside boosts your mood as much as a longer workout.",
    "It's okay to say no to visitors. Your rest and recovery come first.",
  ],
  importData: "Import Data",
  importDesc: "Restore from a previous export file",
  importSuccess: "Data imported successfully!",
  importError: "Could not read file. Please check the format.",
  exportSuccess: "Data exported successfully!",
  resetApp: "Reset App",
  resetDesc: "Delete all data and start fresh",
  resetConfirm: "Are you sure? This will permanently delete all your data including moods, memories, and settings.",
  sleepTracker: "Sleep Log",
  hoursSlept: "Hours:",
  avg: "Avg",
  sleepQuality1: "Terrible",
  sleepQuality2: "Poor",
  sleepQuality3: "Okay",
  sleepQuality4: "Good",
  sleepQuality5: "Great",
  sleepQualityAsk: "How did you sleep?",
  helloName: "Hello, {name}",
  dayStreak: "day streak",
  back: "Back",
  babyBirthDate: "Baby's birth date (optional)",
  week: "Week",
  postpartum: "postpartum",
  monthsOld: "months old",
  clearChatConfirm: "Clear all chat history with Asha?",
  waterTracker: "Water Intake",
  goal: "Goal",
  waterGoalReached: "You hit your water goal today!",
  kegelExercise: "Kegel Exercise",
  kegelDesc: "Strengthen your pelvic floor",
  kegelSqueeze: "Squeeze",
  kegelRelax: "Relax",
  startKegel: "Start 10 Reps",
  reps: "reps",
  today: "today",
  dailyJournal: "Daily Journal",
  journalPlaceholder: "Write your thoughts...",
  saveJournal: "Save Entry",
  journalSaved: "Journal entry saved!",
  journalPrompts: [
    "What made you smile today?",
    "What is one thing you're proud of as a mother?",
    "How has your body felt this week?",
    "What is something kind you can do for yourself today?",
    "Describe a moment with your baby that warmed your heart.",
    "What would you tell another new mom who is struggling?",
    "What is one boundary you want to set this week?",
    "Write about a small victory from today.",
    "How are you really feeling right now? Be honest.",
    "What support do you wish you had more of?",
  ],
  twoMinReset: "2-Minute Reset",
  twoMinResetDesc: "Quick exercises for when you need a moment.",
  reset_grounding: "5-4-3-2-1 Grounding",
  reset_shoulder: "Shoulder Release",
  reset_handOnHeart: "Hand on Heart",
  reset_boxBreathing: "Box Breathing",
  reset_gratitudeReset: "Gratitude Reset",
  reset_bodyScan: "Body Scan",
  reset_tenBreath: "10-Breath Reset",
  reset_nameFeeling: "Name the Feeling",
  reset_microStretch: "Micro Stretch",
  reset_kindSentence: "Kind Sentence",
  done: "Done", next: "Next", startStep: "Start", cycle: "Cycle", breatheTaken: "Breath taken",
  grounding_see: "Name 5 things you can see around you.",
  grounding_touch: "Name 4 things you can touch.",
  grounding_hear: "Name 3 things you can hear.",
  grounding_smell: "Name 2 things you can smell.",
  grounding_feel: "Name 1 thing you feel inside.",
  grounding_done: "You're here. You're present. You're safe.",
  shoulder_step1: "Lift your shoulders up toward your ears. Hold for 5 seconds.",
  shoulder_step2: "Slowly release them down. Let go of the tension.",
  shoulder_step3: "Roll your shoulders backward 5 times, slowly.",
  shoulder_step4: "Take one deep, slow breath.",
  shoulder_done: "Your shoulders feel lighter. Carry on gently.",
  heart_step1: "Place one hand gently on your chest.",
  heart_step2: "Take 3 slow, deep breaths. Feel your heartbeat.",
  heart_step3: "Say silently to yourself...",
  heart_affirmation: "I'm doing my best. That is enough.",
  box_done: "Four cycles complete. Notice how your body feels now.",
  gratitude_prompt: "Name 3 small things that made today a little better.",
  gratitude_example: "something small...",
  body_feet: "your feet", body_legs: "your legs", body_stomach: "your stomach",
  body_shoulders: "your shoulders", body_face: "your face",
  bodyScan_notice: "Gently notice",
  bodyScan_relax: "Breathe into this area. Let it relax.",
  bodyScan_done: "Your whole body is a little more relaxed now.",
  tenBreath_instruction: "Take 10 slow breaths. Tap after each one.",
  tenBreath_done: "10 breaths. You did it. You're calmer now.",
  feeling_prompt: "What are you feeling right now?",
  feeling_overwhelmed: "Overwhelmed", feeling_anxious: "Anxious", feeling_sad: "Sad",
  feeling_tired: "Tired", feeling_calm: "Calm", feeling_grateful: "Grateful",
  feeling_overwhelmed_msg: "It's okay to feel overwhelmed. You're carrying a lot. Take it one moment at a time.",
  feeling_anxious_msg: "Anxiety is your body trying to protect you. You are safe. Breathe slowly.",
  feeling_sad_msg: "Sadness is not weakness. It means you care deeply. Be gentle with yourself.",
  feeling_tired_msg: "Rest is not a luxury — it's a necessity. Can you rest for even 5 minutes?",
  feeling_calm_msg: "What a beautiful moment of peace. You deserve this. Hold onto it.",
  feeling_grateful_msg: "Gratitude is powerful. This feeling is a gift you're giving yourself.",
  stretch_arms: "Stretch your arms up high. Reach for the sky. Hold for 10 seconds.",
  stretch_neck: "Gently tilt your neck left... then right. Hold each side.",
  stretch_wrists: "Rotate your wrists slowly in circles. Release the tension.",
  stretch_done: "A little stretch goes a long way. You took care of your body.",
  kind_prompt: "Write one sentence you would say to a friend in your situation.",
  kind_placeholder: "You are doing better than you think...",
  kind_remember: "Remember this. You deserve your own kindness.",
  reset_visualization: "Safe Place",
  viz_step1: "Close your eyes gently. Take one slow breath.",
  viz_step2: "Picture a place where you feel completely safe and at peace. It could be real or imagined.",
  viz_step3: "Notice the details — what do you see? What sounds are there? What does the air feel like?",
  viz_step4: "Take one more breath. You can visit this place anytime you need.",
  viz_done: "Your safe place is always with you. Return whenever you need a moment of peace.",
  reset_pmr: "Muscle Relaxation",
  pmr_hands: "Hands", pmr_arms: "Arms", pmr_shoulders: "Shoulders",
  pmr_face: "Face", pmr_stomach: "Stomach", pmr_legs: "Legs",
  pmr_tense: "Tense", pmr_release: "Release",
  pmr_done: "Your whole body is more relaxed now. Notice how different you feel.",
  reset_lovingKindness: "Loving-Kindness",
  lk_prompt: "Who would you like to send kindness to?",
  lk_self: "Myself", lk_baby: "My baby", lk_loved: "Someone I love",
  lk_phrase1: "May you be happy.",
  lk_phrase2: "May you be healthy.",
  lk_phrase3: "May you feel safe and loved.",
  lk_done: "You've sent love into the world. That love comes back to you.",
  reset_worryBox: "Worry Box",
  worry_prompt: "Write down one worry that's on your mind. We'll lock it away for now.",
  worry_placeholder: "What's worrying you right now...",
  worry_lock: "Lock it away",
  worry_locking: "Locking your worry away...",
  worry_done: "Your worry is safely stored. You don't need to carry it right now.",
  worry_remember: "You can deal with it later when you're ready — or it may seem smaller by then.",
  reset_selfCompassion: "Self-Compassion",
  sc_step1: "Acknowledge the struggle",
  sc_step1_desc: "Say to yourself: 'This is a hard moment.' Let yourself feel what you're feeling without judgment.",
  sc_step2: "Remember you're not alone",
  sc_step2_desc: "Millions of parents feel this way. Struggling doesn't mean failing — it means you care.",
  sc_step3: "Offer yourself kindness",
  sc_step3_desc: "Place your hand on your heart. Say: 'May I be kind to myself. May I give myself what I need.'",
  sc_done: "You deserve the same compassion you give so freely to others.",
  reset_energyBoost: "Energy Boost",
  energy_move1: "Reach both arms overhead and stretch tall. Big yawn if you can!",
  energy_move2: "March in place — lift those knees! Get the blood flowing.",
  energy_move3: "Shake your hands out fast, like flicking water off. Shake it all out!",
  energy_move4: "Rise on your tiptoes, hold for a moment, then lower. Feel the ground.",
  energy_move5: "Do a tiny happy dance — whatever feels good. No one's watching!",
  energy_done: "Energy unlocked! Even small movements make a big difference.",
  reset_gratitudeLetter: "Gratitude Letter",
  gletter_prompt: "Write a short letter of gratitude — to yourself, your baby, or someone who's helped you.",
  gletter_placeholder: "Dear me, thank you for...",
  gletter_remember: "This letter captures a moment of grace. Save it or carry it in your heart.",
  gletter_saveToVault: "Save to Memory Vault",
  gletter_saved: "Letter saved to your vault!",
  reset_smilePractice: "Smile Practice",
  smile_step1: "Start with a relaxed face. Notice how your face feels right now.",
  smile_step2: "Gently lift the corners of your mouth — just a tiny smile. Hold it.",
  smile_step3: "Let the smile grow a little bigger. Feel the warmth spread to your eyes.",
  smile_step4: "Think of one thing that makes you smile naturally. Hold that thought.",
  smile_done: "Smiling sends a signal to your brain that you're okay. You ARE okay.",
  babyFirsts: "{name}'s Firsts",
  milestonePlaceholder: "First smile, first giggle...",
  milestoneSaved: "Milestone saved!",
  noMilestonesYet: "Log your baby's special firsts here.",

  // Partner Support
  partnerSupport: "Partner & Family",
  partnerIntro: "Partners and family are essential to postpartum recovery. This section is for everyone who supports a new mother.",

  // Mood Insights
  moodInsights: "Your Mood Insights",
  generateInsights: "See My Insights",
  refreshInsights: "Refresh",
  talkToAsha: "Talk to Asha about this",
  lowMoodAlert: "We've noticed you've been feeling low recently. You're not alone, and help is always available.",
  viewHelplines: "View Helplines",
  insightLoading: "Asha is reflecting on your mood patterns...",
  lastUpdated: "Last updated",
  needMoreData: "Log a few more moods to unlock personalized insights.",

  // Nutrition
  nutritionSection: "Nutrition Guide",
  getMealSuggestion: "Get Meal Idea",
  savedToFavorites: "Saved to favorites!",
  removedFromFavorites: "Removed from favorites",
  nutritionProfileLabel: "Your Nutrition Profile",
  breastfeedingLabel: "Breastfeeding",
  dietTypeLabel: "Diet Type",
  culturalPref: "Food Culture",
  allergiesLabel: "Allergies",
  saveProfile: "Save Profile",
  updateProfile: "Edit Profile",
  nutritionTip: "Nutrition Tip",
  loadingMeal: "Asha is thinking of something delicious...",
  noSuggestionsYet: "Tap the button to get a personalized meal idea from Asha.",
  exclusive: "Exclusive",
  partial: "Partial",
  noneBreastfeeding: "None",
  vegetarian: "Vegetarian",
  vegan: "Vegan",
  nonVeg: "Non-Veg",
  pescatarian: "Pescatarian",
  allergiesPlaceholder: "e.g., nuts, dairy...",
  culturalPrefPlaceholder: "e.g., Indian, Mexican...",
  favoriteMeals: "Favorite Meals",

  // Achievements
  achievements: "Mama Milestones",
  achievementsDesc: "Celebrate your journey",
  badge_firstWeekWarrior: "First Week Warrior",
  badge_firstWeekWarrior_desc: "7-day mood logging streak",
  badge_hydrationHero: "Hydration Hero",
  badge_hydrationHero_desc: "Hit 8 glasses 5 times",
  badge_pelvicFloorPro: "Pelvic Floor Pro",
  badge_pelvicFloorPro_desc: "10 kegel sessions completed",
  badge_mindfulMama: "Mindful Mama",
  badge_mindfulMama_desc: "10 reset activities completed",
  badge_memoryKeeper: "Memory Keeper",
  badge_memoryKeeper_desc: "20 memories saved",
  badge_gratitudeGuardian: "Gratitude Guardian",
  badge_gratitudeGuardian_desc: "7 gratitude entries",
  badge_sleepScout: "Sleep Scout",
  badge_sleepScout_desc: "14 sleep logs",
  badge_journalJourney: "Journal Journey",
  badge_journalJourney_desc: "10 journal entries",
  newBadge: "New milestone unlocked! 🎉",

  // Streaks
  wellnessStreak: "wellness streak",
  waterStreakLabel: "water streak",
  journalStreakLabel: "journal streak",
  sunshineStreak: "Sunshine Streak",

  // Quests
  questTitle: "Wellness Quest",
  questActive: "Active Quest",
  questComplete: "Quest Complete! 🎉",
  questStart: "Start Quest",
  questAbandon: "Leave Quest",
  quest_hydrationQuest: "7-Day Hydration",
  quest_hydrationQuest_desc: "Hit 8 glasses daily for 7 days",
  quest_mindfulWeek: "Mindful Week",
  quest_mindfulWeek_desc: "Do 1 reset activity daily for 7 days",
  quest_gratitudeFlow: "Gratitude Flow",
  quest_gratitudeFlow_desc: "Log gratitude daily for 7 days",
  questDay: "Day",

  // Legacy Letters
  legacyLetterTitle: "Letter to Baby",
  legacyLetterSave: "Save to Time Capsule",
  legacyLetterSaved: "Saved to your Time Capsule! 💌",
  legacyLetterPlaceholder: "Write from your heart...",
  legacyLetterPrompts: [
    "What do you wish for your baby's future?",
    "What is one thing you want your baby to always know?",
    "Describe the moment you first held your baby.",
    "What does your baby's laugh sound like to you?",
    "What tradition do you want to pass on?",
    "Write about a hard day that taught you something beautiful.",
    "What does being a mother mean to you right now?",
  ],
};

export function t(key: string): any {
  return strings[key] ?? key;
}
